export type Chat = {
  id: string;
  title: string;

  /**
   * The user that created the chat.
   */
  userId: string;

  /**
   * The project this chat is scoped to, or `null` for chats created before the
   * backend scoped them.
   *
   * Anything resolved *from* a chat — most importantly its citations — must use
   * this rather than the currently selected project: switching projects would
   * otherwise resolve an older chat's citations against the wrong corpus. A chat
   * without a project can no longer be prompted (the backend answers 409).
   */
  projectId: string | null;

  /**
   * Date the chat was created.
   */
  createdAt: string;
};

export type ChatMessage = {
  id: string;

  /**
   * Decides who the message belongs to.
   */
  role: "ASSISTANT" | "USER" | "SYSTEM" | "ORCHESTRATOR";

  /**
   * The chat where the message was posted.
   */
  chat: Chat | undefined;

  /**
   * Text content of the message.
   */
  content: string;

  /**
   * Possible citations appended to the message.
   */
  citations?: Citation[];

  /**
   * Optional reasoning text (e.g.  block) generated by the AI before the final answer.
   * This is only present during live streaming and is not persisted.
   */
  reasoning?: string;

  /**
   * Set to `false` once the stream finishes (done/error/abort). Checked
   * by the UI to decide whether to show the streaming caret. Not persisted —
   * loaded messages from the backend implicitly have `isStreaming: false`.
   */
  isStreaming?: boolean;

  /**
   * Why this turn ended without an answer, when the user is the one who ended it.
   *
   * Failures are deliberately *not* represented here: they surface as a toast
   * (see `ChatProvider`) so a long thread cannot bury them below the fold. This
   * covers the two endings the user caused themselves, where a toast would be
   * noise — they know what they did, the thread just has to say so.
   */
  notice?: ChatNotice;
};

/**
 * The two ways a turn can end without an answer and without a failure.
 *
 * - `stopped` — the user pressed Stop.
 * - `interrupted` — a message was sent into another chat while this answer was
 *   still being written, which is the one case left where a running turn is cut
 *   short (a follow-up in the *same* chat is queued instead — see the chat
 *   queue in `ChatContext`).
 */
export type ChatNotice = "stopped" | "interrupted";

/**
 * A message the user submitted while an answer was still being written.
 *
 * Queued rather than sent: cutting the running answer off mid-sentence to
 * answer a follow-up was the behaviour that made people lose an answer they
 * were reading. Each item keeps the chat it was typed in — the queue drains
 * per chat, so a message queued here can never be sent into a conversation the
 * user has since moved away from.
 *
 * Not persisted: the queue only lives as long as the answer it is waiting
 * behind, and a reload mid-stream abandons that answer anyway. The composer's
 * own draft (localStorage) is the durable half.
 */
export type ChatQueueItem = {
  /** Stable key for React and for removal by id. */
  id: string;
  /** The chat the message was typed in and will be sent to. */
  chatId: string;
  /** The text as the user submitted it — never trimmed, so nothing is silently lost. */
  text: string;
};

export type Citation = {
  /**
   * Id of the artifact (file) the citation refers to.
   */
  artifactId: string;

  /**
   * Name of the file the citation refers to.
   */
  filename: string;

  /**
   * Where the artifact came from (e.g. a GitHub URL), if known.
   */
  sourceUrl?: string;

  /**
   * 1-based source line the citation starts on, for text/code sources.
   */
  startLine?: number;

  /**
   * 1-based page the citation was extracted from, for PDF sources.
   */
  startPage?: number;
};

export type ChatSidebarProps = {
  /**
   * User-created chats displayed in the sidebar.
   */
  chats: Chat[];

  /**
   * Called when the list navigates somewhere — a chat, or a new one.
   *
   * Named for the event rather than for "close the sidebar", because whether it *should* close
   * depends on which of its two shapes the rail is in: a drawer over the conversation has to
   * get out of the way, a column beside it has no reason to. The page owns that decision.
   */
  onNavigate?: () => void;

  /**
   * Optional callback to delete a chat conversation.
   */
  onDeleteChat?: (chatId: string) => Promise<void>;
};

export type StreamHandlers = {
  /**
   * The function executed when the stream event describes a tool used for generating the answer.
   */
  onToolUse: (tool: string) => void;

  /**
   * The function executed when the stream event contains normal text.
   */
  onToken: (token: string) => void;

  /**
   * The function executed when the stream event contains reasoning text (e.g. <think> block).
   */
  onReasoning: (reasoning: string) => void;

  /**
   * The function executed when the stream event is a citation.
   */
  onCitation: (citation: Citation) => void;

  /**
   * The function executed when the stream event marks the end of the stream.
   */
  onDone: () => void;

  /**
   * The function executed when the stream event calls an error.
   */
  onError?: (message: string) => void;
};

export const SOURCE_SYSTEMS = ["GITHUB", "UPLOAD", "JIRA", "CONFLUENCE"] as const;

export type SourceSystem = (typeof SOURCE_SYSTEMS)[number];
