name: Node.js CI

on:
  push:
  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Gitleaks
        run: |
          wget https://github.com/gitleaks/gitleaks/releases/download/v8.30.1/gitleaks_8.30.1_linux_x64.tar.gz
          tar -xzf gitleaks_8.30.1_linux_x64.tar.gz

      - name: Verify Gitleaks
        run: ./gitleaks version

      - name: Scan repository
        run: ./gitleaks detect --verbose --redact

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm install
      - run: npm ci
      - run: npm run lint
      - run: npm run test -- --coverage
      - run: npm run build
      - run: docker build -t sprintstart-frontend .
